version: "3.7"

networks:
  dockerapi-dev:
    driver: bridge #by defult

services:
    admin:
        container_name: 'admin'
        image: admin:latest
        depends_on:
          - "admindb"
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "5000:80"
        environment:
          ASPNETCORE_ENVIRONMENT: Production
        networks:
          - dockerapi-dev  
    admindb:
        container_name: 'admindb'
        image: postgres:latest
        ports:
            - "5432:5432"
        volumes:
            - admindb_volume:/var/lib/postgresql/data
            #- ./seed.sql :/docker-entrypoint-initdb.d/seed.sql
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "password"
        networks:
            - dockerapi-dev
volumes:
    admindb_volume: