version: "3.7"


services:
    admindb:
        container_name: 'admindb'
        image: postgres:latest
        ports:
            - "5432:5432"
        volumes:
            - admindb_volume:/var/lib/postgresql/data
            #- ./seed.sql :/docker-entrypoint-initdb.d/seed.sql
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "password"
volumes:
    admindb_volume:
