name: "db_backup"

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build: 
    name: db_backup
    runs-on: self-hosted
    steps: 
      - name: backup
        run:
          docker exec -t postgres pg_dumpall -c -U postgres > dump_`date +%d-%m-%Y"_"%H_%M_%S`.sql
