name: "dump-db"

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build: 
    name: db_backup
    runs-on: [self-hosted, dump-db]
    steps: 
      - name: dump-db
        run: |
         rm /home/git/backups/*
         cd /home/git/backups
         docker exec -t postgres pg_dumpall -c -U postgres > dump_`date +%d-%m-%Y"_"%H_%M_%S`.sql
