name: "dump-db"

on:
  push:
    branches: [master]
#   schedule:
#     - cron: "0 0 * * *" #midnight

jobs:
  build: 
    name: dump-db
    runs-on: [self-hosted, dump-db]
    steps: 
      - name: dump-db
        run: |
         rm /home/git/backup/*
         cd /home/git/backup
         docker exec -t admindb pg_dumpall -c -U postgres > dump_`date +%d-%m-%Y"_"%H_%M_%S`.sql
