# name: "restore-db"

# on: 
#   workflow_dispatch:
#     inputs:
#       date:
#         description: "Enter date of backup to restore"
#         required: true

# jobs: 
#   get-restore-file: 
#     name: get-backup-file
#     runs-on: [self-hosted, backup-db]
#     steps:
#       - name: scp-file
#         run: |
#           sudo wg-quick up wg0
#           scp /home/backup-runner/backup/dump_${{github.event.inputs.date}}.sql root@10.200.70.1:/home/git/restore/restore.sql
#           sudo wg-quick down wg0
#   restore-db:
#     name: restore
#     runs-on: [self-hosted, dump-db]
#     needs: [get-restore-file]
#     steps:
#       - name: restore
#         run: |
#           docker exec -i admindb psql -U postgres -d postgres < /home/git/restore/restore.sql
#           rm /home/git/restore/restore.sql
